# -*- coding: utf-8 -*-
"""Semana05_01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fDGBAEBkyBEd4y9WoU3uA_JC3itfKckZ

Semana5

Figueroa Gonzalez
"""

# Tuplas
tupla_aula=('Marcani', 'Vegas', 'Figueroa', 'Navarro')
tupla_aula

tupla_aula[2]

len(tupla_aula)

conjunto_aula={'Ramon', 'Moreno', 'Pascacio', 'Luque'}
conjunto_aula

for alumno in conjunto_aula:
  print(alumno)

#observacion: No se acceder por posion pues no considera indexacion

conjunto_aula.add('Muños')
conjunto_aula

conjunto_aula.remove('Luque')
conjunto_aula

#Diccionarios
# Es una coleccion de elementos que estan indexados
# No estan orenados y se pueden modificar
# Son escritos entre llaves y estan formados por pares de elemntos
diccionario_aula={2: 'Muños', '1': 'luque', 'dos': 'Pascasio', '3': 'Navarro', '0': 'lopez'}
diccionario_aula

diccionario_aula['1']

diccionario_aula['20']="Tenorio"
diccionario_aula

diccionario_aula.pop(2)
diccionario_aula

#Otra funconalidad para eliminar elementos dentro de un diccionario
del(diccionario_aula["dos"])
diccionario_aula

for indice in diccionario_aula:
     print(indice)

for indice, valor in diccionario_aula.items():
    print(indice, valor)

'''Ejercicio 1
Dado una lista de {alumnos}
Diseñar un codigo que muestre el resultado si el apellido de un estudiante forma parte de la lista'''
curso=["Figueroa","Garcia","Guitierrez","Isla","Lopez","Luque","Mamani","Marcani","Mondragon","Moreno","Muñoz","Navarro","Otazu","Pascacio","Ramon","Tenorio","Vegas"]
alumno=input("Ingrese el nombre del alumno que desea buscar:")
for nombre in curso:
    if(nombre==alumno):
        print(f"{alumno} se encuentra en la lista")