# -*- coding: utf-8 -*-
"""Semana_05_03.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1M4h2NyE9GzxP-PlcgjsSNRs_m7KqxKUi

Semana 5

Figueroa Gonzalez Giner

tema: Funciones
"""

def saludo():
   print("Bienvenidos al curso de LP3")
   print("### Python ###")
   saludo()

n=int(input("Ingrese un numero: "))
def factorial(numero):
    fac =1
    for i in range(1, numero+1):
        fac*=i
    print(f"El factorial es {fac}")
factorial(n)

def saludo2():
     mensaje ="Bienvenidos a LP3"
     return mensaje
saludo2()

n=int(input("Ingrese un numero :"))
def factorial2(numero):
    fac =1
    for i in range(1,numero+1):
        fac*=i
    return fac

factorial2(n)

def obtenerigv(importe):
    return importe*0.18
obtenerigv(150)

factorial2(5)+10