# -*- coding: utf-8 -*-
"""Semana05_04.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/175xD3ZbIDVu2RprClpP8BmYqn4OXqEtK

**Semana** **5**

Figueroa Gonzalez Giner

tema: clases y objetos
"""

#creamos la clase persona
class Persona:
      nombre=""
      apellidos=""
      dni=""
      talla=0
  #creacion del objeto personal
persona1 = Persona()

  #Asignamos valores al obje
persona1.nombre="Giner"
persona1.apellidos="Figueroa Gonzalez"
persona1.apellidos="74500833"
persona1.talla=1.76

  #Imprimimos la clase
print("Persona1: ")
print(f"Nombre: {persona1.nombre}")
print(f"Apellido: {persona1.apellidos}")
print(f"Dni:{persona1.dni}")
print(f"Talla: {persona1.talla}")

#Problema 02
#Crear la siguiente clase y utilizar constructores:
#Clase: Curso
#Atributos: Codigo,Nombre,Horas,Creaditos
class Curso:
    def __init__(self,codigo,nombre,horas,creditos):
        self.codigo=codigo
        self.nombre=nombre
        self.horas = horas
        self.creditos=creditos
    def mostrar_datos_curso(self):
        print(f"Nombre:{self.nombre}")
        print(f"Codigo: {self.codigo}")
        print(f"Horas: {self.horas}")
        print(f"Creditos: {self.creditos}")
curso1=Curso("C0501","Lp3",6,3)

curso1.mostrar_datos_curso()