# -*- coding: utf-8 -*-
"""Semana5_02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/180jHjIqEmLlherD4u1DthfyBzD8GSqKg

Semana 5

Figueroa Gonzalez Giner
"""

# Problema: Dado el precio de 3 productos ingresados por teclado
#Aplicar un descuentro del 10% si la mayor o igual a 100
p1=float(input("Producto 1:"))
p2=float(input("Producto 2:"))
p3=float(input("Producto 3:"))
venta=p1+p2+p3
if venta >=100 and venta >0:
  print("Se aplicara final el descuento de 10%")
  total=0.9*venta
  print(f"El precio final es {total}")

elif venta<100 and venta>0:

      print(f"El precio final es {venta}")
else:
     print("valor no permitido")

curso=["Figueroa","Garcia","Guitierrez","Isla","Lopez","Luque","Mamani","Marcani","Mondragon","Moreno","Muñoz","Navarro","Otazu","Pascacio","Ramon","Tenorio","Vegas"]
alumno=input("Ingrese el nombre del alumno que desea buscar:")
if alumno in curso:
    print("Si se encuentra en la lista")
else:
    print("No se encuentra en la lista")

'''Problema 2
Dado el importe total de ventas realizados por un trabajador(Ingresados por teclado,
categoria A -->[0, 1000]
categoria B--> <1000, 2000]
categoria C-->< 2000, 5000]
categoria D-->< 5000, Mas])'''
total=float(input("Importe de ventas realizados:"))
if total>0 and total<=1000:
    print("El trabjador es de categoria A")
elif total>0 and total>1000 and total <=2000:
    print("El EL trabajador e sde categoria B")
elif total>0 and total>=2000 and total<=5000:
       print("El trabajador  es de categoria C")
elif  total>0 and total>5000:
    print("El trabajador es de categoria D")
else:
        print("valor no permitido")

cadena=input("Ingresa la cadena: ")
for caracter in cadena:
     print(caracter)

for numero in range(10, 22, 2):
    print(numero)

numero =1
fin=10
while numero<=fin:
  print(numero)
  numero+=1